spring:
  application:
    name: "master-spring-boot"

logging:
    level:
        root: DEBUG
      


# Managment Actuator        
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health, info, beans, threaddump, mappings
  endpoint:
    health:
      show-details: always
      show-components: always
      enabled: true
    info:
      enabled: true
    beans:
      enabled: true
    threaddump:
      enabled: true
    mappings:
      enabled: true

   